config/routes.rb
Rails.application.routes.draw do
  
  # API ROUTES
  namespace :api do
    resources :machines, except: [:new, :edit] do
      resources :products, except: [:new, :edit]
    end
  end
  # END API ROUTES
  
  
  # WEB SIMULATION ROUTES
  namespace :simulator do
    resources :machines, only: [:show, :index]
    post '/buy', to: "machines#buy"
    post '/refill', to: "machines#refill"
  end
  # END WEB SIMULATION ROUTES
  
  
  # WEB APP ROUTES
  devise_for :operators, :controllers => { :registration => "operators_auth/registration" }
  devise_scope :operator do
    get '/login', to: 'devise/sessions#new'
    get '/signup', to: 'devise/registrations#new'
  end
  authenticated :operator do
    root 'machines#index', as: :authenticated_operator_root
  end
  
  resources :machines do
    resources :products
  end
  
  resources :operators, only: [:create, :update] do
    get "/account", to: "operators#account", as: "account"
    get "/generate_secret_token", to: "operators#generate_secret_token"
  end
  
  get "/generate_random", to: "machines#generate_random"
  
  root "machines#index"
  # END WEB APP ROUTES
end

app/models/operator.rb
class Operator < ActiveRecord::Base
    
    # short module to generate a secret token used for minimal authentication
    # for api requests. not quite suitable for production
    module RandomToken
        def self.random(len=32, character_set = ["A".."Z", "a".."z", "0".."9"])
            chars = character_set.map{|x| x.is_a?(Range) ? x.to_a : x }.flatten
            Array.new(len){ chars.sample }.join
        end
    end
    
    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
    
    has_many :machines, dependent: :destroy
    before_create :generate_secret_token
    
    private
    
    # method for generating secret token. ensures uniqueness of each token
    def generate_secret_token
        token = RandomToken.random(15)
        
        until !Operator.exists?(secret_token: token)
          generate_access_token
        end
        
        self.secret_token = token
    end
end

app/controllers/operators/registrations_controller.rb
# frozen_string_literal: true

class Operators::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:password, :password_confirmation, :current_password])
  end
  
  def after_sign_up_path_for(resource)
    root_path
  end
  
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end
  
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
    before_action :authenticate_operator!
    before_action :set_operator, only: [:account, :update, :generate_secret_token]
    
    def update
        @operator.update(operator_params)
        respond_to do |format|
            format.html { redirect_to operator_account_path(@operator), notice: "Your account has been updated!" }
        end
    end
    
    def generate_secret_token
        @operator.update(secret_token: Operator::RandomToken.random(15))
        respond_to do |format|
            format.html { redirect_to operator_account_path(@operator), notice: "New Secret Token Generated!" }
        end
    end
    
    private
    
    def operator_params
        params.require(:operator).permit(:name)
    end
    
    def set_operator
        @operator = current_operator
    end
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/views/operators/account.html.erb
<section id="operator-account">
    <div class="row">
        <div class="col-md-5">
            <div class="card">
                <div class="card-header">
                    Your Account Settings
                </div>
                <div class="card-body">
                    <div id="secret-token">
                        <p>
                            Secret Token: <b><%= @operator.secret_token %></b>
                            <%= link_to "generate new", operator_generate_secret_token_path(@operator), class:"btn btn-link" %>
                        </p>
                    </div>
                    <%= form_for(@operator, :html => { :multipart => true, :id => "operator_form" }) do |f| %>
                        <div class="form-group">
                            <div class="field">
                                <label for="name">Operator</label>
                                <%= f.text_field :name, class:"form-control", placeholder:"name", value:"#{@operator.name if @operator}" %>
                            </div>
                        </div>
                        <div class="actions">
                            <%= f.submit class:"btn btn-success", data: { "disable-with": "Updating your account..." } %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>