config/routes.rb
Rails.application.routes.draw do
  
  # API ROUTES
  namespace :api do
    resources :machines, except: [:new, :edit] do
      resources :products, except: [:new, :edit]
    end
  end
  # END API ROUTES
  
  
  # WEB SIMULATION ROUTES
  namespace :simulator do
    resources :machines, only: [:show, :index]
    post '/buy', to: "machines#buy"
    post '/refill', to: "machines#refill"
  end
  # END WEB SIMULATION ROUTES
  
  
  # WEB APP ROUTES
  devise_for :operators, :controllers => { :registration => "operators_auth/registration" }
  devise_scope :operator do
    get '/login', to: 'devise/sessions#new'
    get '/signup', to: 'devise/registrations#new'
  end
  authenticated :operator do
    root 'machines#index', as: :authenticated_operator_root
  end
  
  resources :machines do
    resources :products
  end
  
  resources :operators, only: [:create, :update] do
    get "/account", to: "operators#account", as: "account"
    get "/generate_secret_token", to: "operators#generate_secret_token"
  end
  
  get "/generate_random", to: "machines#generate_random"
  
  root "machines#index"
  # END WEB APP ROUTES
end

app/models/machine.rb
class Machine < ActiveRecord::Base
    belongs_to :operator
    has_many :products, dependent: :destroy
    has_many :trackers, through: :products
    
    before_create :randomize_location
    
    validates_presence_of :latitude, :longitude unless :not_auto_generated
    
    # machine location by latitude and longitude, for simplicity's sake.
    # future implementations could include full address
    def full_location
        Geocoder.search("#{latitude}, #{longitude}").first.display_name
    end
    
    # machine's current total inventory count from all products
    def total_inventory_count
        products.map(&:current_inventory_count).sum
    end
    
    # all time total items sold
    def total_items_sold
        trackers.map(&:current_value).sum
    end
    
    # this method creates a random number of products ranging from 1 to 6,
    # to fill the machine's slots
    def fill_product_slots(id)
        rand(1..6).times.each do |t|
            Product.create(machine_id: id, threshold: 0, auto_generated: true)
        end
    end
    
    # simple function for randomly generating (installing) an arbitrary number
    # of machines
    def self.generate_random(count, operator)
        machines = []
        count.times.each do |t|
            machines << Machine.create(operator_id: operator.id, auto_generated: true)
        end
        
        machines.each { |m| m.fill_product_slots(m.id) }
    end
    
    # checks if more product slots can be added
    def has_slots_available
        (6 - products.count) > 0
    end
    
    protected
    
    # this method randomizes machine location. latitude and longitude bounds
    # are chosen in order to restrict machine location to NYS area
    def randomize_location
        if self.auto_generated
            self.latitude = rand(40.60000..40.88600)
            self.longitude = rand(-74.08089..-72.21063)
        end
    end
    
    def not_auto_generated
        !self.auto_generated
    end
end

app/controllers/api/machines_controller.rb
# MACHINE API ENDPOINTS

require_relative 'api_controller.rb'

class Api::MachinesController < ApiController
    before_action :set_machine, except: [:index, :create]
    before_action :find_operator
    
    # GET /api/machines
    def index
        @machines = find_operator.machines
        
        render json: @machines
    end
    
    # GET /api/machines/:id
    def show
        render json: @machine
    end
    
    # POST /api/machines
    def create
        @machine = Machine.new(machine_params)
        @machine.operator = find_operator
        @machine.save!
        
        render json: @machine, status: 201
    end
    
    # PUT /api/machines/:id
    def update
        @machine.update(machine_params)
        
        head :no_content
    end
    
    # DELETE /api/machines/:id
    def destroy
        @machine.destroy
        
        head :no_content
    end
    
    private
    
    def machine_params
        params.permit(:longitude, :latitude)
    end
    
    def set_machine
        @machine = Machine.find(params[:id])
    end
    
    def find_operator
        @operator = current_operator || Operator.find_by(secret_token: params[:secret_token])
        
        if @operator.nil?
            render json: { :message => "We were unable to authenticate you" }, :status => 401
        end
    end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :authenticate_operator!
  before_action :set_machine, only: [:show, :edit, :update, :destroy]
  
  # GET machine list
  def index
    @machines = current_operator.machines.order("created_at DESC")
    @machine = Machine.new
  end
  
  # UPDATE machine
  def update
    @machine.update(machine_params)
    respond_to do |format|
      format.html { redirect_to @machine, notice: "Vengo Machine Updated!" }
    end
  end
  
  # CREATE machine
  def create
    @machine = Machine.new(machine_params)
    @machine.operator = current_operator
    
    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: "New Vengo machine added. ID: #{@machine.id}" }
      else
        format.html { redirect_to "/", notice: "Vengo Machine couldn't be added. Please try again!" }
      end
    end
  end
  
  # DELETE machine
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: "Uninstalled machine #{@machine.id}" }
    end
  end
  
  # generate (install) random number of machines
  def generate_random
    Machine.generate_random params[:count].to_i, current_operator
    redirect_to "/", notice: "#{params[:count].to_i} Vengo Machines have been installed!"
  end
  
  private
  
  def set_machine
    @machine = Machine.find(params[:id])
  end
  
  def machine_params
    params.require(:machine).permit(:latitude, :longitude)
  end
end

app/controllers/simulator/machines_controller.rb
class Simulator::MachinesController < ActionController::Base
    layout "simulator/layouts/application"
    before_action :authenticate_operator!
    before_action :set_machine, except: :index
    
    # simulator index page
    def index
        @machines = current_operator.machines
    end
    
    # buy simulator. reduce current inventory count by 1
    def buy
        @product = @machine.products.find(params[:product_id])
        # get old inventory count and new inventory count
        old, new = @product.current_inventory_count, (@product.current_inventory_count - 1)
        # update product
        @product.update(current_inventory_count: new)
        # update tracker
        @product.update_tracker
        
        render :layout => false
    end
    
    # refill simulator. update product inventory count to max capacity
    def refill
        @product = @machine.products.find(params[:product_id])
        max_inventory_count = @product.max_inventory_count
        @product.update(current_inventory_count: max_inventory_count)
        
        render :layout => false
    end
    
    private
    
    def set_machine
        @machine = Machine.find(params[:id])
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_for(@machine, :html => { :multipart => true, :id => "machine_form" }) do |f| %>
    <div class="form-group">
        <div class="field">
            <label for="latitude">Operator</label>
            <p><%= current_operator.name %></p>
        </div>
        <div class="field">
            <label for="latitude">Latitude (defaults to current)</label>
            <%= f.text_field :latitude, class:"form-control", placeholder:"latitude", value:"#{@machine.id ? @machine.latitude : request.location.latitude }" %>
        </div>
        <div class="field">
            <label for="longitude">Longitude (defaults to current)</label>
            <%= f.text_field :longitude, class:"form-control", placeholder:"longitude", value:"#{@machine.id ? @machine.longitude : request.location.longitude }" %>
        </div>
    </div>
    <div class="actions">
        <%= f.submit class:"btn btn-success", data: { "disable-with": "Updating..." } %>
    </div>
<% end %>

app/views/machines/_machines.html.erb
<% machines.each do |m| %>
    <div class="col-md-4" style="margin-bottom: 15px;">
        <div class="card">
            <div class="card-header">
                Machine ID: <%= m.id %>
                <span style="float: right; margin-left: 5px;">
                    <%= link_to machine_path(m), class:"btn btn-danger", title: "Uninstall Machine", method: :delete do %>
                        <i class="fas fa-times"></i>
                    <% end %>
                </span>
                <span style="float: right; margin-left: 5px;">
                    <%= link_to edit_machine_path(m), class:"btn btn-primary", title:"Edit Machine Details" do %>
                        <i class="far fa-edit"></i>
                    <% end %>
                </span>
                <span style="float: right;">
                    <%= link_to machine_path(m), class:"btn btn-success", title: "View Machine Details" do %>
                        <i class="fas fa-search"></i>
                    <% end %>
                </span>
            </div>
            <div class="card-body">
                <section class="overview">
                    <h6 class="text-center">Total Inventory Count</h6>
                    <p class="font-15 text-center"><%= m.total_inventory_count %></p>
                </section>
                
                <hr>
                
                <section class="machine-products">
                    <h6 class="text-center">Inventory Details</h6>
                    <%= render partial: "products/products", locals: { products: m.products } %>
                </section>
            </div>
        </div>
    </div>
<% end %>

app/views/machines/edit.html.erb
<section id="machine-edit">
    <div class="row" style="margin-bottom: 15px;">
        <div class="col-md-4">
            <%= link_to machine_path(@machine), class:"btn btn-primary" do %>
                <i class="fas fa-angle-left"></i> return to machine details
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5">
            <div class="card">
                <div class="card-header">
                    Machine Details
                </div>
                <div class="card-body">
                    <%= render "form" %>
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="card">
                <div class="card-header">
                    Machine Products
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <p class="font-15"><b>Name</b></p>
                        </div>
                        <div class="col-md-3">
                            <p class="font-15"><b>Available</b></p>
                        </div>
                        <div class="col-md-3">
                            <p class="font-15"><b>Capacity</b></p>
                        </div>
                        <div class="col-md-2">
                            <p class="font-15"><b>Threshold</b></p>
                        </div>
                    </div>
                    <div class="row">
                        <% @machine.products.each do |prod| %>
                            <div class="col-md-3">
                                <p class="font-15"><%= prod.name %></p>
                            </div>
                            
                            <div class="col-md-3">
                                <p class="font-15"><%= prod.current_inventory_count %></p>
                            </div>
                            <div class="col-md-3">
                                <p class="font-15"><%= prod.max_inventory_count %></p>
                            </div>
                            <div class="col-md-2">
                                <p class="font-15"><%= prod.threshold %></p>
                            </div>
                            <div class="col-md-1">
                                <%= link_to edit_machine_product_path(@machine, prod), class:"btn btn-link" do %>
                                    <i class="fas fa-pencil-alt"></i>
                                <% end %>
                            </div>
                            <div class="col-md-12">
                                <hr>
                            </div>
                        <% end %>
                        
                        <% if @machine.has_slots_available %>
                            <div class="col-md-12">
                                <%= link_to new_machine_product_path(@machine), class:"btn btn-primary" do %>
                                    <i class="fas fa-plus-circle"></i> add up to 6 products
                                <% end %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/machines/index.html.erb
<section id="dashboard">
    <div class="modal fade" id="addNewMachineModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">New Vengo Machine</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <%= render "machines/form" %>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="bulkInstallation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bulk install a random number of machines</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="/generate_random" data-disable-with="Installing...">
                        <input type="text" class="form-control" name="count"
                            placeholder="how many machines would you like to install?">
                        <button type="submit" class="btn btn-success" style="margin-top: 15px;">
                            Install
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <h6>
        Machines in use: <span style="color: blue;"><%= @machines.count %></span>
        <span style="margin-left: 10px;">
            [<a href="#" data-toggle="modal" data-target="#addNewMachineModal"
                class="btn btn-link" style="padding: 0;">
                install a new machine</a>]
        </span>
        <span style="margin-left: 10px;">
            [<a data-toggle="modal" data-target="#bulkInstallation" href="#"
                class="btn btn-link" style="padding: 0;">
                bulk installation</a>]
        </span>
        <span style="margin-left: 10px;">
            [<a href="/" class="btn btn-link" style="padding: 0;">
                reload dashboard</a>]
        </span>
    </h6>
    
    <hr>
    
    <div class="row">
        <% if @machines.present? %>
            <%= render partial: "machines", locals: { machines: @machines } %>
        <% else %>
            <div class="col-md-12">
                <p>No machine to track</p>
            </div>
        <% end %>
    </div>
</section>

app/views/machines/show.html.erb
<section class="machine-show">
    <div class="row">
        <div class="col-md-8">
            <h4>
                Machine ID: <%= @machine.id %>
                <span style="margin-left: 15px;" class="badge badge-warning <%= some_need_refill @machine %>">
                    some/all products need refill
                </span>
                <span style="margin-left: 15px;" class="badge badge-danger <%= some_need_restock @machine %>">
                    some/all products are out of stock
                </span>
            </h4>
        </div>
        
        <div class="col-md-4">
            <%= link_to edit_machine_path(@machine), class:"btn btn-primary" do %>
                Edit <i class="fas fa-pencil-alt"></i>
            <% end %>
            
            <%= link_to machine_path(@machine), class:"btn btn-danger", method: :delete do %>
                Remove <i class="fas fa-times"></i>
            <% end %>
            
            <%= link_to simulator_machine_path(@machine), class:"btn btn-success" do %>
                Web Simlulator <i class="fas fa-terminal"></i>
            <% end %>
        </div>
    </div>
    
    <hr>
    
    <p>
        <span>
            <b>Location</b>:
            <%= @machine.full_location %>
        </span>
    </p>
    
    <p>
        <span>
            <b>Operator</b>:
            <%= @machine.operator.name %>
        </span>
    </p>
    
    <p>
        <span>
            <b>Total Inventory Count</b>:
            <%= @machine.total_inventory_count %> (current)
        </span>
    </p>
    
    <p>
        <span>
            <b>Total Items Sold</b>:
            <%= @machine.total_items_sold %>
        </span>
    </p>
    
    <hr>
    
    <div class="row">
        <div class="col-md-12 text-center">
            <h5>
                Inventory Breakdown
                <% if @machine.has_slots_available %>
                    <span style="margin-left: 5px;">
                        [<%= link_to "add new product", new_machine_product_path(@machine),
                            class:"btn btn-link" %>]
                    </span>
                <% end %>
            </h5>
        </div>
        
        <div class="col-md-2">
            <p class="font-15"><b>Name</b></p>
        </div>
        <div class="col-md-2">
            <p class="font-15"><b>Available</b></p>
        </div>
        <div class="col-md-2">
            <p class="font-15"><b>Capacity</b></p>
        </div>
        <div class="col-md-2">
            <p class="font-15"><b>Sold</b></p>
        </div>
        <div class="col-md-2">
            <p class="font-15"><b>Status</b></p>
        </div>
        <div class="col-md-2">
            <p class="font-15"><b>Last Sold</b></p>
        </div>
        <% @machine.products.each do |prod| %>
            <div class="col-md-2">
                <p class="font-15"><%= prod.name %></p>
            </div>
            
            <div class="col-md-2">
                <p class="font-15"><%= prod.current_inventory_count %></p>
            </div>
            <div class="col-md-2">
                <p class="font-15"><%= prod.max_inventory_count %></p>
            </div>
            <div class="col-md-2">
                <p class="font-15"><%= prod.total_sold %></p>
            </div>
            <div class="col-md-2">
                <p class="font-15 <%= prod.status.downcase.split(' ').join('-') %>">
                    <b><%= prod.status %></b>
                </p>
            </div>
            <div class="col-md-2">
                <p class="font-15"><%= prod.updated_at.strftime("%b %e %Y - %l:%M %p") %></p>
            </div>
        <% end %>
        
        <% if @machine.products.any? {|prod| prod.threshold == 0} %>
            <div class="col-md-12">
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    Some or all of these products have a threshold of 0. It's better
                    to have a threshold above 0 to avoid out-of-stock status.
                    [<%= link_to edit_machine_path(@machine), class:"btn btn-link", style: "padding: 0;" do %>
                        Edit Products
                    <% end %>]
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        <% end %>
    </div>
</section>