config/routes.rb
Rails.application.routes.draw do
  
  # API ROUTES
  namespace :api do
    resources :machines, except: [:new, :edit] do
      resources :products, except: [:new, :edit]
    end
  end
  # END API ROUTES
  
  
  # WEB SIMULATION ROUTES
  namespace :simulator do
    resources :machines, only: [:show, :index]
    post '/buy', to: "machines#buy"
    post '/refill', to: "machines#refill"
  end
  # END WEB SIMULATION ROUTES
  
  
  # WEB APP ROUTES
  devise_for :operators, :controllers => { :registration => "operators_auth/registration" }
  devise_scope :operator do
    get '/login', to: 'devise/sessions#new'
    get '/signup', to: 'devise/registrations#new'
  end
  authenticated :operator do
    root 'machines#index', as: :authenticated_operator_root
  end
  
  resources :machines do
    resources :products
  end
  
  resources :operators, only: [:create, :update] do
    get "/account", to: "operators#account", as: "account"
    get "/generate_secret_token", to: "operators#generate_secret_token"
  end
  
  get "/generate_random", to: "machines#generate_random"
  
  root "machines#index"
  # END WEB APP ROUTES
end

app/views/layouts/_base_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">vengo-tracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="btn btn-secondary" href="/signup">
                    Sign Up
                </a>
            </li>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<footer>
    <div class="row">
        <div class="col-md-12 text-center">
            &copy; Demesvar Destin | vengo-tracker
        </div>
    </div>
</footer>

app/views/layouts/_operator_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">vengo-tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="btn btn-link" href="/">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-link" href="/simulator/machines">Web Simulator</a>
                </li>
                <li class="nav-item">
                    <div class="dropdown">
                        <button class="btn btn-secondary" type="button"
                            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= current_operator.name || "Edit Your Profile" %> <i class="fas fa-angle-down"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <%= link_to "Account Settings", operator_account_path(current_operator), class:"dropdown-item" %>
                            <div class="dropdown-divider"></div>
                            <%= link_to destroy_operator_session_path, class:"dropdown-item", method: :delete do %>
                                Log Out <i class="fas fa-sign-out-alt"></i>
                            <% end %>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>vengo-tracker</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.rawgit.com/oauth-io/oauth-js/c5af4519/dist/oauth.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <%= csrf_meta_tags %>
  </head>
  
  <body>
    <%= render navbar %>
    
    <section class="block-content container">
      <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      
      <%= yield %>
    </section>
    
    <%= render footer %>
    
  </body>
  
</html>